var especialidades = [];
var pacientes = [
  {
    documento: 96732338,
    nombre: "Marcos",
    apellido: "Roman",
    edad: 31,
    mail: "mroman@mail.com",
    contrasenia: "96732338",
    telefono: 94382546,
    direccion: "Republica de Chile 9267",
    estado: true,
    foto: "4.png",
    altura: 180,
    peso: 76,
    pesoMin: 74,
    pesoMax: 76,
    imc: 23.456790123456788
  },
  {
    documento: 95704499,
    nombre: "Emma",
    apellido: "Saez",
    edad: 19,
    mail: "esaez@mail.com",
    contrasenia: "95704499",
    telefono: 96331071,
    direccion: "Neptuno 7336",
    estado: true,
    foto: "9.png",
    altura: 170,
    peso: 68,
    pesoMin: 67,
    pesoMax: 70,
    imc: 23.529411764705884
  },
  {
    documento: 96539605,
    nombre: "Silvia",
    apellido: "Mora",
    edad: 34,
    mail: "smora@mail.com",
    contrasenia: "96539605",
    telefono: 98967797,
    direccion: "Colombes 5989",
    estado: true,
    foto: "10.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 4161876,
    nombre: "Ismael",
    apellido: "Domenech",
    edad: 27,
    mail: "idomenech@mail.com",
    contrasenia: "4161876",
    telefono: 95246960,
    direccion: "Sarandí 2341",
    estado: true,
    foto: "4.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 12817079,
    nombre: "Roberto",
    apellido: "Sanchez",
    edad: 36,
    mail: "rsanchez@mail.com",
    contrasenia: "12817079",
    telefono: 96918916,
    direccion: "Ansina 2562",
    estado: true,
    foto: "6.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 16226644,
    nombre: "Natalia",
    apellido: "Serrano",
    edad: 21,
    mail: "nserrano@mail.com",
    contrasenia: "16226644",
    telefono: 93631891,
    direccion: "Brisas 4805",
    estado: true,
    foto: "3.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 54187995,
    nombre: "Álvaro",
    apellido: "Molina",
    edad: 19,
    mail: "amolina@mail.com",
    contrasenia: "54187995",
    telefono: 91233653,
    direccion: "Ibirapita 5809",
    estado: true,
    foto: "11.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 15139113,
    nombre: "José",
    apellido: "Ferrer",
    edad: 54,
    mail: "jferrer@mail.com",
    contrasenia: "15139113",
    telefono: 96331071,
    direccion: "Neptuno 7336",
    estado: true,
    foto: "8.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 46224305,
    nombre: "Miriam",
    apellido: "Navarro",
    edad: 40,
    mail: "mnavarro@mail.com",
    contrasenia: "46224305",
    telefono: 93693734,
    direccion: "Costanera 8644",
    estado: true,
    foto: "2.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
  {
    documento: 43363227,
    nombre: "Anna",
    apellido: "Pastor",
    edad: 21,
    mail: "apastor@mail.com",
    contrasenia: "43363227",
    telefono: 93557127,
    direccion: "Florianapolis 3407",
    estado: true,
    foto: "1.png",
    altura: 0,
    peso: 0,
    pesoMin: 0,
    pesoMax: 0,
    imc: 0
  },
];
var medicos = [
  {
    profesional: 0595,
    nombre: "Diana",
    apellido: "Peña",
    especialidad: "Psiquiatría",
    mail: "dpena@mail.com",
    contrasenia: "0595",
    consultas: 4,
    estado: true
  },
  {
    profesional: 4833,
    nombre: "Santiago",
    apellido: "Vicente",
    especialidad: "Oftalmología",
    mail: "svicente@mail.com",
    contrasenia: "4833",
    consultas: 7,
    estado: true
  },
  {
    profesional: 4467,
    nombre: "Berta",
    apellido: "Blanco",
    especialidad: "Ginecología",
    mail: "bblanco@mail.com",
    contrasenia: "4467",
    consultas: 0,
    estado: true
  },
  {
    profesional: 0739,
    nombre: "Raúl",
    apellido: "Medina",
    especialidad: "Psiquiatría",
    mail: "rmedina@mail.com",
    contrasenia: "0739",
    consultas: 0,
    estado: true
  },
  {
    profesional: 8576,
    nombre: "Jesús",
    apellido: "Campos",
    especialidad: "Medicina General",
    mail: "jcampos@mail.com",
    contrasenia: "8576",
    consultas: 10,
    estado: true
  },
  {
    profesional: 5517,
    nombre: "Gerard",
    apellido: "Gallardo",
    especialidad: "Cardiología",
    mail: "ggallardo@mail.com",
    contrasenia: "5517",
    consultas: 0,
    estado: true
  },
  {
    profesional: 5068,
    nombre: "Isaac",
    apellido: "Sanchez",
    especialidad: "Neurología",
    mail: "isanchez@mail.com",
    contrasenia: "5068",
    consultas: 0,
    estado: true
  },
  {
    profesional: 8822,
    nombre: "José",
    apellido: "Serrano",
    especialidad: "Medicina General",
    mail: "jserrano@mail.com",
    contrasenia: "8822",
    consultas: 23,
    estado: true
  },
  {
    profesional: 7656,
    nombre: "Patricia",
    apellido: "Alvarez",
    especialidad: "Pediatría",
    mail: "palvarez@mail.com",
    contrasenia: "7656",
    consultas: 0,
    estado: true
  },
  {
    profesional: 4106,
    nombre: "Claudia",
    apellido: "Diaz",
    especialidad: "Pediatría",
    mail: "cdiaz@mail.com",
    contrasenia: "4106",
    consultas: 0,
    estado: true
  }
];
var consultas = [
{
    id: "dpen1",
    medico: 595,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
},
{
    id: "svic2",
    medico: 4833,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
},
{
    id: "jcam3",
    medico: 8576,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
},
{
    id: "jser4",
    medico: 8822,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
},
{
    id: "palv5",
    medico: 7656,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
},
{
    id: "rmed6",
    medico: 739,
    paciente: 96732338,
    estado: true,
    pago: true,
    observacion: "Chequeos correctos."
},
{
    id: "dpen7",
    medico: 595,
    paciente: 16226644,
    estado: false,
    pago: true,
    observacion: ""
},
{
    id: "dpen8",
    medico: 595,
    paciente: 96732338,
    estado: false,
    pago: false,
    observacion: ""
}
];
